title: Mariya Mego
description: About Mariya
author: Mariya Mego
github: https://github.com/mash-a
about: I craft projects in JavaScript and React.
google_analytics: UA-131810282-1
avatar_url: /static/img/profile.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
  - icon: fa-twitter
    link: "https://twitter.com/masha_codes"
  - icon: fa-linkedin
    link: "https://www.linkedin.com/in/mariya-mego-vela/"
  - icon: fa-github
    link: "https://github.com/mash-a"

share:
  twitter_username: masha_codes
  fb_appid: 1749788565247320

urls:
  - text: About Me
    url: /about/
  - text: My Projects
    url: /projects/

url: "https://mash-a.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ["development"]
